"""Atualizando Identity (PostgreSQL)

Revision ID: 04d9d3842783
Revises: 941ea3dceb32
Create Date: 2025-10-09 13:29:00.428944
"""

from alembic import op
import os

revision = "04d9d3842783"
down_revision = "941ea3dceb32"
branch_labels = None
depends_on = None

SCHEMA = os.getenv("DB_SCHEMA", "public")
TABLES = [
    "language_room_users",
    "languages",
    "rooms",
    "speakers",
    "users",
]


def upgrade() -> None:
    for tbl in TABLES:
        # 1) se já for identity, não faz nada
        # 2) se tiver DEFAULT (ex.: nextval de SERIAL), remove
        # 3) adiciona IDENTITY BY DEFAULT
        op.execute(
            f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = '{SCHEMA}'
          AND table_name   = '{tbl}'
          AND column_name  = 'id'
          AND is_identity  = 'YES'
    ) THEN
        -- já é identity
        NULL;
    ELSE
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema   = '{SCHEMA}'
              AND table_name     = '{tbl}'
              AND column_name    = 'id'
              AND column_default IS NOT NULL
        ) THEN
            ALTER TABLE "{SCHEMA}"."{tbl}" ALTER COLUMN id DROP DEFAULT;
        END IF;

        ALTER TABLE "{SCHEMA}"."{tbl}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
"""
        )

    # (opcional) garantir NOT NULL explicitamente
    for tbl in TABLES:
        op.execute(f'ALTER TABLE "{SCHEMA}"."{tbl}" ALTER COLUMN id SET NOT NULL;')

    # (opcional) garantir PK em id (caso tenha sido removida em alguma tabela)
    # Ajuste se seus nomes de PK forem diferentes
    for tbl in TABLES:
        op.execute(
            f"""
DO $$
BEGIN
    -- Cria PK em (id) se não existir nenhuma PK
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints tc
        WHERE tc.table_schema = '{SCHEMA}'
          AND tc.table_name   = '{tbl}'
          AND tc.constraint_type = 'PRIMARY KEY'
    ) THEN
        ALTER TABLE "{SCHEMA}"."{tbl}" ADD CONSTRAINT "{tbl}_pkey" PRIMARY KEY (id);
    END IF;
END $$;
"""
        )


def downgrade() -> None:
    # Reverte apenas removendo o IDENTITY (não recriamos DEFAULT/SEQUENCE antigo)
    for tbl in TABLES:
        op.execute(
            f'ALTER TABLE "{SCHEMA}"."{tbl}" ALTER COLUMN id DROP IDENTITY IF EXISTS;'
        )
