"""Mudando relação sala usuario e linguagem

Revision ID: 131a42be7c36
Revises: 435b62577678
Create Date: 2025-10-09 11:13:42.171886
"""

from alembic import op
import sqlalchemy as sa

revision = '131a42be7c36'
down_revision = '435b62577678'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_room_users', sa.Column('source_language_id', sa.Integer(), nullable=False))
    op.add_column('language_room_users', sa.Column('target_language_id', sa.Integer(), nullable=True))
    op.alter_column('language_room_users', 'role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_language_room_users_language_id_languages'), 'language_room_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_language_room_users_target_language_id_languages'), 'language_room_users', 'languages', ['target_language_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_language_room_users_source_language_id_languages'), 'language_room_users', 'languages', ['source_language_id'], ['id'], ondelete='CASCADE')
    op.drop_column('language_room_users', 'language_id')
    op.drop_constraint(op.f('fk_rooms_origin_language_id_languages'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'origin_language_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('origin_language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_rooms_origin_language_id_languages'), 'rooms', 'languages', ['origin_language_id'], ['id'], ondelete='CASCADE')
    op.add_column('language_room_users', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_language_room_users_source_language_id_languages'), 'language_room_users', type_='foreignkey')
    op.drop_constraint(op.f('fk_language_room_users_target_language_id_languages'), 'language_room_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_language_room_users_language_id_languages'), 'language_room_users', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.alter_column('language_room_users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('language_room_users', 'target_language_id')
    op.drop_column('language_room_users', 'source_language_id')
    # ### end Alembic commands ###
