"""Migracao inicial

Revision ID: 1d21cca38fc6
Revises: 
Create Date: 2025-09-28 21:39:25.439172
"""

from alembic import op
import sqlalchemy as sa

revision = '1d21cca38fc6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('code', name=op.f('uq_languages_code'))
    )
    op.create_table('rooms',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_speaker', sa.Boolean(), nullable=False),
    sa.Column('is_translator', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('speakers',
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speakers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speakers'))
    )
    op.create_index(op.f('ix_speakers_user_id'), 'speakers', ['user_id'], unique=True)
    op.create_table('translators',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_translators_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translators'))
    )
    op.create_index(op.f('ix_translators_user_id'), 'translators', ['user_id'], unique=True)
    op.create_table('language_speakers',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_language_speakers_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_language_speakers_speaker_id_speakers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'speaker_id', 'id', name=op.f('pk_language_speakers'))
    )
    op.create_table('language_translators',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('translator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_language_translators_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translator_id'], ['translators.id'], name=op.f('fk_language_translators_translator_id_translators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'translator_id', 'id', name=op.f('pk_language_translators'))
    )
    op.create_table('room_speakers',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_speakers_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_room_speakers_speaker_id_speakers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'speaker_id', 'id', name=op.f('pk_room_speakers'))
    )
    op.create_table('room_translators',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('translator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_translators_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translator_id'], ['translators.id'], name=op.f('fk_room_translators_translator_id_translators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'translator_id', 'id', name=op.f('pk_room_translators'))
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_translators')
    op.drop_table('room_speakers')
    op.drop_table('language_translators')
    op.drop_table('language_speakers')
    op.drop_index(op.f('ix_translators_user_id'), table_name='translators')
    op.drop_table('translators')
    op.drop_index(op.f('ix_speakers_user_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('languages')
    # ### end Alembic commands ###
