"""Adicionando role para relação

Revision ID: 435b62577678
Revises: 861953e29917
Create Date: 2025-10-09 10:41:41.677971
"""

from alembic import op
import sqlalchemy as sa

revision = '435b62577678'
down_revision = '861953e29917'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_room_users', sa.Column('role', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_room_users', 'role')
    # ### end Alembic commands ###
