"""Adicionado relação entre linguagem e sala

Revision ID: 4a2b8d5f8c0b
Revises: ca0385904376
Create Date: 2025-10-08 20:03:25.186878
"""

from alembic import op
import sqlalchemy as sa

revision = '4a2b8d5f8c0b'
down_revision = 'ca0385904376'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_rooms',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_language_rooms_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_language_rooms_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'room_id', 'id', name=op.f('pk_language_rooms'))
    )
    op.add_column('rooms', sa.Column('origin_language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_rooms_origin_language_id_languages'), 'rooms', 'languages', ['origin_language_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rooms_origin_language_id_languages'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'origin_language_id')
    op.drop_table('language_rooms')
    # ### end Alembic commands ###
