"""Ajustando tabelas pivo

Revision ID: 861953e29917
Revises: af0063a9b087
Create Date: 2025-10-09 10:18:48.770624
"""

from alembic import op
import sqlalchemy as sa

revision = '861953e29917'
down_revision = 'af0063a9b087'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_room_users', 'id')
    op.drop_column('language_speakers', 'id')
    op.drop_column('language_translators', 'id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_translators', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('language_speakers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('language_room_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
