"""Atualizando tabelas

Revision ID: 941ea3dceb32
Revises: 131a42be7c36
Create Date: 2025-10-09 11:40:39.544252
"""

from alembic import op
import sqlalchemy as sa

revision = '941ea3dceb32'
down_revision = '131a42be7c36'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_room_users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_language_room_users_room_id'), 'language_room_users', ['room_id'], unique=False)
    op.create_index(op.f('ix_language_room_users_source_language_id'), 'language_room_users', ['source_language_id'], unique=False)
    op.create_index(op.f('ix_language_room_users_target_language_id'), 'language_room_users', ['target_language_id'], unique=False)
    op.create_index(op.f('ix_language_room_users_user_id'), 'language_room_users', ['user_id'], unique=False)
    op.create_unique_constraint('ux_lru_unique_role_link', 'language_room_users', ['room_id', 'user_id', 'role', 'source_language_id', 'target_language_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_lru_unique_role_link', 'language_room_users', type_='unique')
    op.drop_index(op.f('ix_language_room_users_user_id'), table_name='language_room_users')
    op.drop_index(op.f('ix_language_room_users_target_language_id'), table_name='language_room_users')
    op.drop_index(op.f('ix_language_room_users_source_language_id'), table_name='language_room_users')
    op.drop_index(op.f('ix_language_room_users_room_id'), table_name='language_room_users')
    op.drop_column('language_room_users', 'id')
    # ### end Alembic commands ###
