"""Atualizando tabelas

Revision ID: 9d12d02e5bc0
Revises: 04d9d3842783
Create Date: 2025-10-09 13:56:14.041586
"""

from alembic import op
import sqlalchemy as sa

revision = '9d12d02e5bc0'
down_revision = '04d9d3842783'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_room_users', 'id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_room_users', sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
