"""Alterando relações sala linguagem e usuario

Revision ID: af0063a9b087
Revises: 4a2b8d5f8c0b
Create Date: 2025-10-09 08:24:09.819332
"""

from alembic import op
import sqlalchemy as sa

revision = 'af0063a9b087'
down_revision = '4a2b8d5f8c0b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_room_users',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_language_room_users_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_language_room_users_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_language_room_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'room_id', 'user_id', 'id', name=op.f('pk_language_room_users'))
    )
    op.drop_table('room_translators')
    op.drop_table('room_speakers')
    op.drop_table('language_rooms')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_rooms',
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_language_rooms_language_id_languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_language_rooms_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'room_id', 'id', name=op.f('pk_language_rooms'))
    )
    op.create_table('room_speakers',
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_speakers_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_room_speakers_speaker_id_speakers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'speaker_id', 'id', name=op.f('pk_room_speakers'))
    )
    op.create_table('room_translators',
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('translator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_translators_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translator_id'], ['translators.id'], name=op.f('fk_room_translators_translator_id_translators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'translator_id', 'id', name=op.f('pk_room_translators'))
    )
    op.drop_table('language_room_users')
    # ### end Alembic commands ###
